<div class="top-bar">
    <nav class="top-bar-left">
        <div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="large">
            <button class="menu-toggle" type="button" data-toggle="offCanvas" aria-label="<?php echo $this->translate('Menu'); ?>"><i class="fas fa-bars"></i></button>
            <?php echo $this->partial('common/site-title', ['site' => $site, 'siteUrl' => $siteUrl, 'siteTitle' => $siteTitle]); ?>
        </div>
        <a href="#" class="contribute button">This site is part of <em>Locating Legacies of Slavery</em>. Learn more here.</a>
    </nav>
</div>