<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$fragment = 'item-linked';
if ('Omeka\Api\Representation\ItemSetRepresentation' === get_class($objectResource)) {
    $fragment = 'item-set-linked';
}
$pagination = $this->pagination(null, $totalCount, $page, $perPage);
$pagination->setFragment($fragment);

if ($this->status()->isSiteRequest()) {
    $filterLocale = (bool) $this->siteSetting('filter_locale_values');
    $lang = $this->lang();
} else {
    $filterLocale = false;
    $lang = null;
}
?>
<div id="linked-resources">


<?php foreach ($subjectValues as $term => $values): ?>
    <?php foreach ($values as $value): ?>
        <?php echo $value['val']->resource()->linkPretty('square', null, null, null, ($filterLocale ? $lang : null)); ?>
    <?php endforeach; ?>
</tbody>
</table>
<?php endforeach; ?>

<?php echo ($totalCount > $perPage) ? '<div class="linked-footer">' . $pagination . '</div>' : ''; ?>

</div>

<script>
$('#filter-property').on('change', function(e) {
    var thisSelect = $(this);
    var property = thisSelect.find(':selected').val();
    var url = thisSelect.data('url');
    var fragment = thisSelect.data('fragment');
    window.location = url + '?' + $.param({property: property}) + '#' + fragment;
});
</script>
