<style>
    <?php
    ($bodyBgColor = $this->themeSetting('body_bg_color')) || ($bodyBgColor = "#f2f2f2");
    ($contentBgColor = $this->themeSetting('content_bg_color')) || ($contentBgColor = "#ffffff");
    ($linkColor = $this->themeSetting('link_color')) || ($linkColor = "#1c6896");
    ($visitedLinkColor = $this->themeSetting('visited_link_color')) || ($visitedLinkColor = "#1c6896");
    ($activeLinkColor = $this->themeSetting('active_link_color')) || ($activeLinkColor = "#c9cff5");
    ($activeLinkTextColor = $this->themeSetting('active_link_text_color')) || ($activeLinkTextColor = "#1c6896");
    ($headerLinkColor = $this->themeSetting('header_link_color')) || ($headerLinkColor = "#1c6896");
    ($headerVisitedLinkColor = $this->themeSetting('header_visited_link_color')) || ($headerVisitedLinkColor = "#1c6896");
    ($headerActiveLinkColor = $this->themeSetting('header_active_link_color')) || ($headerActiveLinkColor = "#c9cff5");
    ($headerActiveLinkTextColor = $this->themeSetting('header_active_link_text_color')) || ($headerActiveLinkTextColor = "#1c6896");
    ($buttonColor = $this->themeSetting('button_bg_color')) || ($buttonColor = "#1c6896");
    ($buttonTextColor = $this->themeSetting('button_text_color')) || ($buttonTextColor = "#fefefe");
    ($buttonHoverTextColor = $this->themeSetting('button_hover_text_color')) || ($buttonHoverTextColor = "#1c6896");
    ($buttonHoverBackgroundColor = $this->themeSetting('button_hover_background_color')) || ($buttonHoverBackgroundColor = "#1c6896");
    ($headerBackgroundColor = $this->themeSetting('header_background_color')) || ($headerBackgroundColor = "#ffffff");
    ($footerBackgroundColor = $this->themeSetting('footer_background_color')) || ($footerBackgroundColor = "#ffffff");
    ($searchBackgroundColor = $this->themeSetting('search_background_color')) || ($searchBackgroundColor = "#ffffff");

    ?>

    a:link {
        color: <?php echo $linkColor; ?>;
    }

    a:not(.button):visited {
        color: <?php echo $visitedLinkColor; ?>;
    }

    a:hover, a:active, a:focus {
        color: <?php echo $activeLinkTextColor; ?>;
        background-color: <?php echo $activeLinkColor; ?>;
    }

    .button, a.button, button, .button[disabled],.button[disabled]:hover,
    input[type="reset"],
    input[type="submit"],
    input[type="button"],
    .site-page-pagination a,
    .site-page-pagination a:not(.button):visited {
        background-color: <?php echo $buttonColor; ?>;
        color: <?php echo $buttonTextColor; ?>;
    }

    .button:hover, button:hover,
    input[type="reset"]:hover,
    input[type="submit"]:hover,
    input[type="button"]:hover,
    .site-page-pagination a:hover {
        background-color: <?php echo $buttonHoverBackgroundColor; ?>;
        color: <?php echo $buttonHoverTextColor; ?>;
    }     

    body {
        background-color: <?php echo $bodyBgColor; ?>;
    }

    <?php if ($this->themeSetting('body_bg_image') !== null): ?>
    body:after {
        background: url('<?php echo $this->themeSettingAssetUrl('body_bg_image'); ?>') center/cover no-repeat; 
    }
    <?php endif; ?>

    header.main,
    .top-bar ul ul {
        background-color: <?php echo $headerBackgroundColor; ?>;
        border-color: transparent;
    }

    header.main a:link,
    #respponsive-menu a:link {
        color: <?php echo $headerLinkColor; ?>;
    }

    header.main a:not(.button):visited,
    #res a:not(.button):visited {
        color: <?php echo $headerVisitedLinkColor; ?>;
    }

    header.main a:hover, 
    header.main a:active, 
    header.main a:focus, 
    #respponsive-menu a:hover, 
    #respponsive-menu a:active, 
    #respponsive-menu a:focus {
        color: <?php echo $headerActiveLinkTextColor; ?>;
        background-color: <?php echo $headerActiveLinkColor; ?>;
    }

    footer {
        background-color: <?php echo $footerBackgroundColor; ?>;
    }

    #responsive-menu:after,
    .dropdown.menu > li.is-dropdown-submenu-parent.active:hover > a {
        background-color: <?php echo $searchBackgroundColor; ?>;
    }

    #content {
        background-color: <?php echo $contentBgColor; ?>;
    }
    
    .dropdown.menu > li.is-active > a {
        border-color: <?php echo $activeLinkTextColor; ?> transparent transparent;
    }

    .dropdown.menu > li.is-dropdown-submenu-parent > a:after {
        border-color: <?php echo $headerLinkColor; ?> transparent transparent;
    }              
</style>