<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
$showLayout = $this->themeSetting('show_layout');

$customMetadata = [
    'Types' => $item->value('dcterms:type',['all' => true]),
    'Categories' => $item->value('mare:categoricalFocus',['all' => true]),
    'Places' => $item->value('mare:populatedPlaceName',['all' => true]),
    'States' => $item->value('mare:stateTerritoryName',['all' => true]),
    'Countries' => $item->value('mare:countryName',['all' => true]),
    'Geographic Focus' => $item->value('mare:geographicalFocus',['all' => true]),
    'Material Focus' => $item->value('mare:materialFocus',['all' => true]),
    'Accrual Method' => $item->value('dcterms:accrualMethod',['all' => true]),
]
?>

<!-- Metadata for everything else. -->
<div class="grid-x grid-padding-x">

    <div class="resource-title cell medium-12">
        <?php echo $this->pageTitle($item->displayTitle(), 2); ?>
    </div>

    <div class="cell medium-12">
        <?php foreach ($itemMedia as $media): ?>
            <?php echo $media->render(); ?>
        <?php endforeach; ?>
    </div>

    <div class="cell medium-9">
        <?php $this->trigger('view.show.before'); ?>
        <?php echo $item->displayValues(); ?>

        <?php $itemSets = $item->itemSets(); ?>
        <?php if (count($itemSets) > 0): ?>
            <div class="property">
            <h4>Item Sets</h4>
            <div class="values">
            <?php foreach ($itemSets as $itemSet): ?>
            <a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a>
            <?php endforeach; ?>
            </div>
            </div>
        <?php endif; ?>

        <?php
        $page = $this->params()->fromQuery('page', 1);
        $property = $this->params()->fromQuery('property');
        $subjectValues = $item->displaySubjectValues($page, 25, $property);
        ?>
        <?php if ($subjectValues): ?>
        <div id="item-linked">
            <h3><?php echo $translate('Linked resources'); ?></h3>
            <?php echo $subjectValues; ?>
        </div>
        <?php endif; ?>

        <?php $this->trigger('view.show.after'); ?>
    </div>
</div>



