<?php
$escape = $this->plugin('escapeHtml');
$stylesheet = $this->themeSetting('stylesheet');
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->prependStylesheet($this->assetUrl('css/collecting.css'));

$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headScript()->prependFile('//cdn.jsdelivr.net/npm/foundation-sites@6.5.3/dist/js/foundation.min.js', 'text/javascript', [
  'integrity' => 'sha256-/PFxCnsMh+nTuM0k3VJCRch1gwnCfKjaP8rJNq5SoBg= sha384-9ksAFjQjZnpqt6VtpjMjlp2S0qrGbcwF/rvrLUg2vciMhwc1UJJeAAOLuJ96w+Nj sha512-UMSn6RHqqJeJcIfV1eS2tPKCjzaHkU/KqgAnQ7Nzn0mLicFxaVhm9vq7zG5+0LALt15j1ljlg8Fp9PT1VGNmDw==',
  'crossorigin' => 'anonymous'
]);
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$title = $this->pageTitle($site->title());
$userBar = $this->userBar();

if ($userBar) {
  $this->htmlElement('body')->appendAttribute('class', 'user-bar');
}

$logo = $this->themeSettingAssetUrl('logo');
if ($logo):
    $title = '<img src="' . $this->escapeHtml($logo) . '">';
endif;
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>

        <style>
           <?php
            ($linkColor = $this->themeSetting('link_color')) || ($linkColor = "#1c6896");
            ($visitedLinkColor = $this->themeSetting('visited_link_color')) || ($visitedLinkColor = "#1c6896");
            ($activeLinkColor = $this->themeSetting('active_link_color')) || ($activeLinkColor = "#c9cff5");
            ($activeLinkTextColor = $this->themeSetting('active_link_text_color')) || ($activeLinkTextColor = "#1c6896");
            ($buttonColor = $this->themeSetting('button_bg_color')) || ($buttonColor = "#1c6896");
            ($buttonTextColor = $this->themeSetting('button_text_color')) || ($buttonTextColor = "#fefefe");
            ($buttonHoverTextColor = $this->themeSetting('button_hover_text_color')) || ($buttonHoverTextColor = "#1c6896");
            ($buttonHoverBackgroundColor = $this->themeSetting('button_hover_background_color')) || ($buttonHoverBackgroundColor = "#1c6896");

            ?>
                
                a:link {
                    color: <?php echo $linkColor; ?>;
                }
                a:visited {
                    color: <?php echo $visitedLinkColor; ?>;
                }
                a:hover, a:active, a:focus {
                    color: <?php echo $activeLinkTextColor; ?>;
                    background-color: <?php echo $activeLinkColor; ?>;
                }
                
        
                .button, button, .button[disabled],.button[disabled]:hover,
                input[type="reset"],
                input[type="submit"],
                input[type="button"] {
                  background-color: <?php echo $buttonColor; ?>;
                  color: <?php echo $buttonTextColor; ?> !important;
                }
                .button:hover, button:hover,
                input[type="reset"]:hover,
                input[type="submit"]:hover,
                input[type="button"]:hover {
                  background-color: <?php echo $buttonHoverBackgroundColor; ?>;
                  color: <?php echo $buttonHoverTextColor; ?> !important;
                }                   
        </style>
    </head>

    <?php echo $this->htmlElement('body'); ?>
    
        <div id="offCanvas" class="off-canvas position-left" data-off-canvas>
            <?php echo $site->publicNav()->menu()->setPartial('common/foundation-navigation.phtml')->renderPartialWithParams(['layout' => 'vertical']); ?>
            <div class="search">
                <?php echo $this->partial('common/search-form'); ?>
            </div>
        </div>
        <div class="off-canvas-content" data-off-canvas-content>
            <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
            <?php echo $userBar; ?>
            <header>
                <?php echo $this->partial('common/header-dropdown'); ?>
            </header>
            <div class="grid-container">           
                <?php if ($this->themeSetting('logo')): ?>
                <a href="<?php echo $site->url(); ?>" class="site-title"><img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" title="Logo"></a>
                <?php else: ?>
                <a href="<?php echo $site->url(); ?>" class="site-title"><?php echo $this->pageTitle($site->title()); ?></a>
                <?php endif; ?>
            </div>
            <div id="content" role="main">
                <?php echo $this->content; ?>
            </div>
            <footer>
                <div class="grid-x grid-margin-x">
                <?php if ($footerLogoOne = $this->themeSettingAssetUrl('footer_logo_one')): ?>
                    <div class="cell auto">
                        <img src="<?php echo $this->escapeHtml($footerLogoOne); ?>">
                    </div>
                <?php endif; ?>
                <?php if ($footerLogoTwo = $this->themeSettingAssetUrl('footer_logo_two')): ?>
                    <div class="cell auto">
                        <img src="<?php echo $this->escapeHtml($footerLogoTwo); ?>">
                    </div>
                <?php endif; ?>
                <?php if ($footerLogoThree = $this->themeSettingAssetUrl('footer_logo_three')): ?>
                    <div class="cell auto">
                        <img src="<?php echo $this->escapeHtml($footerLogoThree); ?>">
                    </div>
                <?php endif; ?>
                <?php if ($footerLogoFour = $this->themeSettingAssetUrl('footer_logo_four')): ?>
                    <div class="cell auto">
                        <img src="<?php echo $this->escapeHtml($footerLogoFour); ?>">
                    </div>
                <?php endif; ?>

                <div class="cell small-12">
                <?php if ($footerContent = $this->themeSetting('footer')): ?>
                    <?php echo $footerContent; ?>
                <?php else: ?>
                    <?php echo $this->translate('Powered by Omeka S'); ?>
                <?php endif; ?>
                </div>
                </div>
            </footer>
        </div>
        <script>
          $(document).foundation();
        </script>
    </body>
</html>
