<?php
$escape = $this->plugin('escapeHtml');
$stylesheet = $this->themeSetting('stylesheet');
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->prependStylesheet($this->assetUrl('css/legacies.css'));

$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headScript()->prependFile('//cdn.jsdelivr.net/npm/foundation-sites@6.5.3/dist/js/foundation.min.js', 'text/javascript', [
  'integrity' => 'sha256-/PFxCnsMh+nTuM0k3VJCRch1gwnCfKjaP8rJNq5SoBg= sha384-9ksAFjQjZnpqt6VtpjMjlp2S0qrGbcwF/rvrLUg2vciMhwc1UJJeAAOLuJ96w+Nj sha512-UMSn6RHqqJeJcIfV1eS2tPKCjzaHkU/KqgAnQ7Nzn0mLicFxaVhm9vq7zG5+0LALt15j1ljlg8Fp9PT1VGNmDw==',
  'crossorigin' => 'anonymous'
]);
$this->headLink()->prependStylesheet('//cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css');
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$title = $this->pageTitle($site->title());
$userBar = $this->userBar();
$siteUrl = $site->url();
$siteTitle = $site->title();
$this->jsTranslate();

if ($userBar) {
  $this->htmlElement('body')->appendAttribute('class', 'user-bar');
}

$logo = $this->themeSettingAssetUrl('logo');
if ($logo):
    $title = '<img src="' . $this->escapeHtml($logo) . '">';
endif;
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>

        <style>
           <?php
            ($bodyBgColor = $this->themeSetting('body_bg_color')) || ($bodyBgColor = "#f2f2f2");
            ($contentBgColor = $this->themeSetting('content_bg_color')) || ($contentBgColor = "#ffffff");
            ($linkColor = $this->themeSetting('link_color')) || ($linkColor = "#1c6896");
            ($visitedLinkColor = $this->themeSetting('visited_link_color')) || ($visitedLinkColor = "#1c6896");
            ($activeLinkColor = $this->themeSetting('active_link_color')) || ($activeLinkColor = "#c9cff5");
            ($activeLinkTextColor = $this->themeSetting('active_link_text_color')) || ($activeLinkTextColor = "#1c6896");
            ($buttonColor = $this->themeSetting('button_bg_color')) || ($buttonColor = "#1c6896");
            ($buttonTextColor = $this->themeSetting('button_text_color')) || ($buttonTextColor = "#fefefe");
            ($buttonHoverTextColor = $this->themeSetting('button_hover_text_color')) || ($buttonHoverTextColor = "#1c6896");
            ($buttonHoverBackgroundColor = $this->themeSetting('button_hover_background_color')) || ($buttonHoverBackgroundColor = "#1c6896");

            ?>

                body {
                    background-color: <?php echo $bodyBgColor; ?>;
                }

                #content {
                    background-color: <?php echo $contentBgColor; ?>;
                }
                
                a:link {
                    color: <?php echo $linkColor; ?>;
                    border-color: <?php echo $linkColor; ?>;
                }
                a:not(.button):visited {
                    color: <?php echo $visitedLinkColor; ?>;
                    border-color: <?php echo $visitedLinkColor; ?>;
                }
                a:hover, a:active, a:focus, .dropdown.menu > li.is-active > a, .dropdown.menu > li.is-dropdown-submenu-parent > a:after {
                    color: <?php echo $activeLinkTextColor; ?>;
                    background-color: <?php echo $activeLinkColor; ?>;
                    border-color: <?php echo $activeLinkTextColor; ?>;
                }
                
        
                .button, a.button, button, .button[disabled],.button[disabled]:hover,
                input[type="reset"],
                input[type="submit"],
                input[type="button"] {
                  background-color: <?php echo $buttonColor; ?>;
                  color: <?php echo $buttonTextColor; ?>;
                }
                .button:hover, button:hover,
                input[type="reset"]:hover,
                input[type="submit"]:hover,
                input[type="button"]:hover {
                  background-color: <?php echo $buttonHoverBackgroundColor; ?>;
                  color: <?php echo $buttonHoverTextColor; ?>;
                }                   
        </style>
    </head>

    <?php echo $this->htmlElement('body'); ?>
    
        <div id="offCanvas" class="off-canvas position-left" data-off-canvas>
            <?php echo $site->publicNav()->menu()->setPartial('common/foundation-navigation.phtml')->renderPartialWithParams(['layout' => 'vertical']); ?>
            <div class="search">
                <?php echo $this->partial('common/search-form'); ?>
            </div>
        </div>
        <div class="off-canvas-content" data-off-canvas-content>
            <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
            <?php echo $userBar; ?>
            <header id="link-back">
                <?php echo $this->partial('common/header-dropdown', ['site' => $site, 'siteUrl' => $siteUrl, 'siteTitle' => $siteTitle]); ?>
            </header>
            <header class="main grid-container">           
                <?php echo $this->partial('common/site-title', ['site' => $site, 'siteUrl' => $siteUrl, 'siteTitle' => $siteTitle]); ?>
            </header>
            <div id="content" role="main">
                <?php echo $this->content; ?>
            </div>
            <footer>
                <div class="logos">
                    <?php $footerLogos = [
                         $this->themeSettingAssetUrl('footer_logo_one') => $this->themeSetting('footer_logo_link_one'),
                         $this->themeSettingAssetUrl('footer_logo_two') => $this->themeSetting('footer_logo_link_two'),
                         $this->themeSettingAssetUrl('footer_logo_three') => $this->themeSetting('footer_logo_link_three'),
                         $this->themeSettingAssetUrl('footer_logo_four') => $this->themeSetting('footer_logo_link_four')
                    ] ?>
                    <?php foreach ($footerLogos as $key => $value): ?>
                        <?php if($value): ?>
                            <a href="<?php echo $this->escapeHtml($value); ?>"><img src="<?php echo $this->escapeHtml($key); ?>"></a>
                        <?php elseif($key != null): ?>
                            <img src="<?php echo $this->escapeHtml($key); ?>">
                        <?php endif; ?>
                    <?php endforeach; ?>

                   
                    
                </div>

                <?php if ($footerContent = $this->themeSetting('footer')): ?>
                    <?php echo $footerContent; ?>
                <?php else: ?>
                    <?php echo $this->translate('Powered by Omeka S'); ?>
                <?php endif; ?>
                </div>
            </footer>
        </div>
        <script>
          $(document).foundation();
        </script>
    </body>
</html>
